name: corsac_http_application
version: 0.1.0-dev
description: HTTP application framework
homepage: https://github.com/corsac-dart/http-application
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  logging: "^0.11.2"
  corsac_kernel:
    git: https://github.com/corsac-dart/kernel.git
  corsac_router:
    git: https://github.com/corsac-dart/router.git
  corsac_middleware:
    git: https://github.com/corsac-dart/middleware.git

dev_dependencies:
  test: "^0.12.6+1"
  mockito: "^0.11.0"
