name: corsac_rpc
version: 0.1.0
description: Extensible HTTP API application server based on Dart's rpc package and Corsac components
homepage: https://github.com/corsac-dart/rpc
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  rpc: "^0.5.5"
  logging: "^0.11.2"
  corsac_kernel:
    git: https://github.com/corsac-dart/kernel.git
  corsac_router:
    git: https://github.com/corsac-dart/router.git
  corsac_middleware:
    git: https://github.com/corsac-dart/middleware.git

dev_dependencies:
  test: "^0.12.6+1"
  mockito: "^0.11.0"
